# ConfigMap to expose configuration related to backend application
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf # name of configMap
data:
        server-uri: 44.208.30.203:30001 # enternal ip of backend application 'Service'
