apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: to-do-app-frontend
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: to-do-app-frontend
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
